### ISSUE TITLE
About画面の設計・実装

### ISSUE THREAD

**Issue by syokun** [syokun/Creams#14]
# 概要
ログインする前の画面
# 目的
どのようなサービスかを紹介する画面

**Comment by syokun** [comment]
# 進捗
`PowerPoint`で画面デザイン作成

# 作成画像
![about](https://user-images.githubusercontent.com/18301085/36139618-962e8444-10e1-11e8-8268-0e1f7b6ada40.png)

# ボタンでの画面遷移
* ロゴを押すとtopへ遷移
    * ログイン前はabout画面へ、ログイン後はtop画面へ
* ログイン・新規登録ボタンを押すとログイン画面へ

# 今後の予定
フッターを作るかどうか考え中

**Comment by hisakioomae** [comment]
おおおお，いいね〜

**Comment by syokun** [comment]
# 進捗内容
* rootへアクセスするとabout画面に遷移
* about画面に紹介ページ掲載

# aboutページ
<img width="1280" alt="2018-02-14 19 07 09" src="https://user-images.githubusercontent.com/18301085/36198592-5879b7a2-11ba-11e8-96e4-6ddd52ec4f00.png">

# 今後の予定
* ヘッダーを追加してtopとloginへの遷移リンク作成

**Comment by hisakioomae** [comment]
お疲れ様です！
