### ISSUE TITLE
Slackとの連携

### ISSUE THREAD

**Issue by hisakioomae** [syokun/Creams#18]
# 概要
Slackへ、プルリク作成およびissue作成において通知が行くように連携してください。
つまり、GitHubにおけて、プルリク作成およびissue作成時をtriggerとして、つうちするということです。

**Comment by syokun** [comment]
# 進捗
slackと連携
（テストも兼ねて）

# 参考サイト
[GitHubのpushやプルリク通知をSlackに投げる](https://qiita.com/unsoluble_sugar/items/072c9740e258ee93ff9a)

**Comment by hisakioomae** [comment]
お疲れ様でした
[![LGTM](https://www.lgtm.in/p/aV8CIHT8q)](https://www.lgtm.in/i/aV8CIHT8q)
