### ISSUE TITLE
Readmeの開発環境へ開発環境図を追加

### ISSUE THREAD

**Issue by hisakioomae** [syokun/Creams#23]
# 概要
タイトル通り

# 開発環境
- LocalPC
- Github
- CircleCI
- Slack
- Heroku

上記の5つの遷移図(環境図)を追加してください．
powerpoint，cacco...

**Comment by syokun** [comment]
# 進捗
`PowerPoint`で開発環境図作成

# 作成画像
<img width="960" alt="default" src="https://user-images.githubusercontent.com/18301085/36339386-5156b9a8-1407-11e8-904c-fa30e0f95df2.png">

### たたき台なんでツッコミお待ちしてます

**Comment by hisakioomae** [comment]
pushは多いのでいいかな
もっとマージン広く

**Comment by hisakioomae** [comment]
それが終わればいい感じの図じゃないでしょうか

**Comment by syokun** [comment]
# 進捗
マージン広く

# 作成画像
![default](https://user-images.githubusercontent.com/18301085/36339530-6c9f4168-140b-11e8-9264-5e770e3bb7d1.png)

**Comment by hisakioomae** [comment]
OK〜

**Comment by hisakioomae** [comment]
それをReadmeに貼りましょうか
