### ISSUE TITLE
Top画面からの画面遷移図

### ISSUE THREAD

**Issue by hisakioomae** [syokun/Creams#6]
# 概要
Top画面からの大まかな画面遷移図の作成
# 提案内容
`cacco` 使用しますか?
`powerpoint` 使用しますか?

# 参考
- スライドシェア機能画面
- カレンダー画面(勉強会企画提案画面)
- カレンダー画面(勉強会企画成立画面)
- アンケート(要望)画面
- コントリビュータ画面
- スタッフ画面
- 設定画面
- お問い合わせ画面

**Comment by syokun** [comment]
# 進捗
全体的な画面遷移図を作成

# 使用ツール
`PowerPoint`

# 作成図
![default](https://user-images.githubusercontent.com/18301085/36137588-4d7a1298-10d9-11e8-8af9-165d16fdc918.png)

# 補足
①のtopページはサービスの紹介ページで、④のtopページはマイページのようなものを考えています。

**Comment by hisakioomae** [comment]
いい感じですね！
PullRequestあげちゃいましょう！

**Comment by hisakioomae** [comment]
about画面に変えれます？

**Comment by hisakioomae** [comment]
日本語なので英語にしましょうか
1. about
2. login
3. signup
4. top
5. schedule
6. slideshare
7. setting
8. question
9. questionnaire

**Comment by hisakioomae** [comment]
こういうフォルダ構成にしたいので

**Comment by syokun** [comment]
# 進捗
日本語を英語に

# 作成図
![default](https://user-images.githubusercontent.com/18301085/36140937-600349f4-10e6-11e8-9dc6-d94b461416f0.png)

# 質問
> PullRequestあげちゃいましょう！
READMEに追加ってこと？
