### ISSUE TITLE
アプリのロゴ画像作成

### ISSUE THREAD

**Issue by hisakioomae** [syokun/Creams#7]
# 概要
タイトル通りです

**Comment by syokun** [comment]
# 進捗
タイトルロゴ作成
試作第一号

# 作成画像
![logo](https://user-images.githubusercontent.com/18301085/36059357-a3686e4a-0e7a-11e8-99c4-2b7833868791.png)

# 工夫点
可愛らしいアイコンにしたかったので、フラットデザイン をメインに作成しました。
"Creams"という名前から連想しやすいソフトクリーム の画像を使用しました。

# 懸念点
文字の解像度があまり高くないので、拡大して使用する場合は画像が粗くなるかも…

# 参考サイト
[手書きメーカー](http://tegaki-maker.com/)
[FLAT ICON DESIGN](http://flat-icon-design.com/?p=455)

**Comment by hisakioomae** [comment]
クソワロw
Readmeを変更するプルリク投げて，issueと結び告げてマージしちゃいましょう
